title: OrganizeMe
description: ""

exclude:
  - node_modules
  - package.json
  - package-lock.json
  - yarn.lock
  - pnpm-lock.yaml
  - README.md
  - android
  - ios
  - dist
  - build
  - public
  - .github
  - .gitignore

liquid:
  error_mode: warn
  strict_filters: false
